version: '3'

services: 
  front-end:
    build: 
      context: .
    container_name: front-end
    working_dir: /home/proud/Documents/autism-fight-club/src
    networks: 
      - node-network
    volumes: 
      - ./:/home/proud/Documents/autism-fight-club/src
      - /home/proud/Documents/autism-fight-club/node_modules
    tty: true
    ports: 
      - "5173:5173"
    command: npm run dev

  nginx:
    build: 
      context: .
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - node-network
    depends_on:
      - front-end
    
networks: 
  node-network:
    driver: bridge